export const login_image = require('./login-img.png')
export const cmp_logo = require('./brand-logo.svg').default
export const cmp_icon = require('./brand-icon.svg').default
export const login_net = require('./login-dots.svg').default

export const toggleicon = require('./toggle-ic.svg').default
export const dashboard = require('./dash-default.svg').default
export const dashboardnew = require('./dash-active.svg').default
export const users = require('./users-default.svg').default
export const usersnew = require('./users-active.svg').default
export const history = require('./time-default.svg').default
export const historynew = require('./time-active.svg').default
export const maintenance = require('./maintenance-default.svg').default
export const maintenancenew = require('./maintenance-active.svg').default
export const inbox = require('./inbox-default.svg').default
export const inboxnew = require('./inbox-active.svg').default
export const analyze = require('./analyze-default.svg').default
export const analyzenew = require('./analyze-active.svg').default
export const setting = require('./setting-default.svg').default
export const settingnew = require('./setting-active.svg').default
export const dollar = require('./dollar-ic.svg').default
export const star = require('./star-ic.svg').default
export const layer = require('./disc-ic.svg').default
export const money_bag = require('./money-bag-ic.svg').default
export const add_product = require('./add-product-ic.svg').default
export const black_arrow = require('./blackarrow-ic.svg').default
export const datagraph = require('./data-graph.svg').default
export const country_sales = require('./pie-chart.svg').default
export const searchicon = require('./search-ic.svg').default
export const notification = require('./notification.svg').default
export const profile = require('./profile.png')

export const upload_icon = require('./upload-ic.svg') .default
export const error = require('./ic-error.svg') .default
export const info = require('./ic-info.svg') .default
export const valid = require('./ic-success.svg') .default
export const warn = require('./ic-warn.svg') .default
export const select_arrow = require('./select-arrow.svg') .default 
// export const check = require('./check-tick.svg') .default
